//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FoxTTS.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FoxTTS.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT TTS插件.
        /// </summary>
        internal static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        internal static string buttonCheckUpdate {
            get {
                return ResourceManager.GetString("buttonCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开下载页面.
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略错误（插件将无法正常工作）.
        /// </summary>
        internal static string buttonIgnore {
            get {
                return ResourceManager.GetString("buttonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        internal static string buttonIgnoreVersion {
            get {
                return ResourceManager.GetString("buttonIgnoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 听听看!.
        /// </summary>
        internal static string buttonPreview {
            get {
                return ResourceManager.GetString("buttonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置为默认设置.
        /// </summary>
        internal static string buttonResetToDefault {
            get {
                return ResourceManager.GetString("buttonResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载上一次的设置.
        /// </summary>
        internal static string buttonRestoreFromBackup {
            get {
                return ResourceManager.GetString("buttonRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稍后.
        /// </summary>
        internal static string buttonUpdateLater {
            get {
                return ResourceManager.GetString("buttonUpdateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string buttonUpdateNow {
            get {
                return ResourceManager.GetString("buttonUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检查更新.
        /// </summary>
        internal static string checkBoxCheckUpdate {
            get {
                return ResourceManager.GetString("checkBoxCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出时清空 TTS 缓存.
        /// </summary>
        internal static string checkBoxClearCacheExit {
            get {
                return ResourceManager.GetString("checkBoxClearCacheExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只提示稳定版更新.
        /// </summary>
        internal static string checkBoxNotifyStableOnly {
            get {
                return ResourceManager.GetString("checkBoxNotifyStableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件集成.
        /// </summary>
        internal static string groupBoxIntegration {
            get {
                return ResourceManager.GetString("groupBoxIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放设置.
        /// </summary>
        internal static string groupBoxPlayback {
            get {
                return ResourceManager.GetString("groupBoxPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 声音预览.
        /// </summary>
        internal static string groupBoxPreview {
            get {
                return ResourceManager.GetString("groupBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS 引擎.
        /// </summary>
        internal static string groupBoxTTSEngine {
            get {
                return ResourceManager.GetString("groupBoxTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引擎详情.
        /// </summary>
        internal static string groupBoxTTSEngineDetail {
            get {
                return ResourceManager.GetString("groupBoxTTSEngineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件更新.
        /// </summary>
        internal static string groupBoxUpdate {
            get {
                return ResourceManager.GetString("groupBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        internal static string labelApiKey {
            get {
                return ResourceManager.GetString("labelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本:.
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新稳定版本:.
        /// </summary>
        internal static string labelLatestStableVersion {
            get {
                return ResourceManager.GetString("labelLatestStableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新版本:.
        /// </summary>
        internal static string labelLatestVersion {
            get {
                return ResourceManager.GetString("labelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言:.
        /// </summary>
        internal static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主音量:.
        /// </summary>
        internal static string labelMasterVolume {
            get {
                return ResourceManager.GetString("labelMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *需要重启ACT。.
        /// </summary>
        internal static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人声选择:.
        /// </summary>
        internal static string labelPerson {
            get {
                return ResourceManager.GetString("labelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音调:.
        /// </summary>
        internal static string labelPitch {
            get {
                return ResourceManager.GetString("labelPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出设备:.
        /// </summary>
        internal static string labelPlaybackDevice {
            get {
                return ResourceManager.GetString("labelPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放 API:.
        /// </summary>
        internal static string labelPlaybackMethod {
            get {
                return ResourceManager.GetString("labelPlaybackMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key:.
        /// </summary>
        internal static string labelSecretKey {
            get {
                return ResourceManager.GetString("labelSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语速:.
        /// </summary>
        internal static string labelSpeed {
            get {
                return ResourceManager.GetString("labelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引擎:.
        /// </summary>
        internal static string labelTTSEngine {
            get {
                return ResourceManager.GetString("labelTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音量:.
        /// </summary>
        internal static string labelVolume {
            get {
                return ResourceManager.GetString("labelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理设置.
        /// </summary>
        internal static string lblProxy {
            get {
                return ResourceManager.GetString("lblProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即清空缓存.
        /// </summary>
        internal static string linkLabelClearCache {
            get {
                return ResourceManager.GetString("linkLabelClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册 API 密钥.
        /// </summary>
        internal static string linkLabelOpenBaiduReg {
            get {
                return ResourceManager.GetString("linkLabelOpenBaiduReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开缓存文件夹.
        /// </summary>
        internal static string linkLabelOpenCacheDir {
            get {
                return ResourceManager.GetString("linkLabelOpenCacheDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设为推荐值.
        /// </summary>
        internal static string linkLabelSetRecommend {
            get {
                return ResourceManager.GetString("linkLabelSetRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定要删除所有缓存的音频吗？.
        /// </summary>
        internal static string messageAskClearCache {
            get {
                return ResourceManager.GetString("messageAskClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓存已删除。.
        /// </summary>
        internal static string messageCacheCleared {
            get {
                return ResourceManager.GetString("messageCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前已是最新版！.
        /// </summary>
        internal static string messageLatest {
            get {
                return ResourceManager.GetString("messageLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新的抢鲜版: {0}。.
        /// </summary>
        internal static string messageNewPrerelease {
            get {
                return ResourceManager.GetString("messageNewPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新的稳定版: {0}。.
        /// </summary>
        internal static string messageNewStable {
            get {
                return ResourceManager.GetString("messageNewStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT 原生 TTS.
        /// </summary>
        internal static string radioButtonIntegrationAct {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检测.
        /// </summary>
        internal static string radioButtonIntegrationAuto {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hojoring 语音合成 (TTSYukkuri).
        /// </summary>
        internal static string radioButtonIntegrationYukkuri {
            get {
                return ResourceManager.GetString("radioButtonIntegrationYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 ACT 的设置进行回放.
        /// </summary>
        internal static string radioButtonPlaybackACT {
            get {
                return ResourceManager.GetString("radioButtonPlaybackACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 TTSYukkuri 的设置进行回放.
        /// </summary>
        internal static string radioButtonPlaybackYukkuri {
            get {
                return ResourceManager.GetString("radioButtonPlaybackYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法加载当前的设置文件！.
        /// </summary>
        internal static string settingsError {
            get {
                return ResourceManager.GetString("settingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一次的设置文件备份也无法加载！.
        /// </summary>
        internal static string settingsErrorBackup {
            get {
                return ResourceManager.GetString("settingsErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你可以：
        ///1. 重置为默认设置，注意这将导致当前设置丢失！
        ///2. 直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！.
        /// </summary>
        internal static string settingsErrorHintNoBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintNoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你可以：
        ///1.从上一次的设置备份中恢复，注意这将导致当前设置丢失！
        ///2.重置为默认设置，这也将导致当前设置丢失！
        ///3.直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！.
        /// </summary>
        internal static string settingsErrorHintWithBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintWithBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规设置.
        /// </summary>
        internal static string tabPageGeneralSettings {
            get {
                return ResourceManager.GetString("tabPageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件日志.
        /// </summary>
        internal static string tabPageLog {
            get {
                return ResourceManager.GetString("tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日はいい天気ですね。.
        /// </summary>
        internal static string textBoxPreview {
            get {
                return ResourceManager.GetString("textBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiCloud语音.
        /// </summary>
        internal static string ttsEngineAiCloud {
            get {
                return ResourceManager.GetString("ttsEngineAiCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百度语音.
        /// </summary>
        internal static string ttsEngineBaidu {
            get {
                return ResourceManager.GetString("ttsEngineBaidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查中....
        /// </summary>
        internal static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string versionUnknown {
            get {
                return ResourceManager.GetString("versionUnknown", resourceCulture);
            }
        }
    }
}
