name: Build artifact

on:
  push:
    paths:
      - 'ACT.FoxTTS/**'
      - 'MSBuild.ILMerge.Task.targets'
      - '.github/matchers/msbuild.json'
      - '.github/workflows/build-artifact.yml'
  # 
  workflow_dispatch:
    inputs:
      version:
        description: 'version number in filename'
        required: true
        default: ''
      info:
        description: 'explain what is changed'
        required: true
        default: ''

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Set up msbuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Add Custom Problem Matcher
      run: |
        echo "::add-matcher::.github/matchers/msbuild.json"
    
    - name: NuGet restore
      run: |
        nuget restore .\ACT.FoxTTS\ACT.FoxTTS.sln

    - name: MSBuild
      shell: cmd
      run: |
        cp MSBuild.ILMerge.Task.targets .\ACT.FoxTTS\packages\MSBuild.ILMerge.Task.1.1.3\build\MSBuild.ILMerge.Task.targets
        msbuild /p:Configuration=Release /p:Platform="Any CPU" ACT.FoxTTS/ACT.FoxTTS.sln

    - name: Generate artifact
      run: |
        mkdir -p ./publish
        cp ./ACT.FoxTTS/ACT.FoxTTS/bin/Release/ACT.FoxTTS.dll publish/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ACT.FoxTTS-release
        path: publish/

  publish:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [ build ]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ACT.FoxTTS-release
        path: publish/

    - name: Archive Release
      run: |
        zip -j release.zip ./publish/*
        7z a release.7z ./publish/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.info }}
        body: ''
        draft: false
        prerelease: true

    - name: Upload Zip Release Asset
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: ACT.FoxTTS-release-${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip

    - name: Upload 7zip Release Asset
      id: upload-release-asset-7z
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.7z
        asset_name: ACT.FoxTTS-release-${{ github.event.inputs.version }}.7z
        asset_content_type: application/x-7z-compressed
